#!/bin/sh

. /etc/formfactor/config

if [ "$HAVE_TOUCHSCREEN" = "1" ]; then
    SHOWCURSOR="no"
else
    SHOWCURSOR="yes"
fi

matchbox-desktop &

# Lines containing feature-[foo] are removed at build time if the machine
# doesn't have the feature "foo".

START_APPLETS=showdesktop,windowselector
END_APPLETS=clock,battery,systray,startup-notify,notify

matchbox-panel --titlebar --end-applets=$END_APPLETS &
matchbox-panel --geometry=x40+0-40 --fullscreen --end-applets $START_APPLETS &

exec matchbox-window-manager -theme "Sato-mod" -use_desktop_mode decorated -use_cursor no $@
